resources:
   repositories:
     - repository: build_pipeline
       type: github
       endpoint: Jwatts30
       name: Jwatts30/lambdatest

stages:
  - stage: job1
    displayName: job1
    jobs:
    - job: github
      displayName: github
      steps:
        - checkout: build_pipeline
          displayName: ABC
          

      

